# Generated by Django 3.2.4 on 2021-07-09 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DZ', '0002_auto_20210620_1823'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AddField(
            model_name='review',
            name='author',
            field=models.CharField(max_length=255, null=True, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
    ]
